Importação de dados e exploração inicial

Primeiro tópico:

In [73]:
import pandas as pd
import numpy as np

varejo = pd.read_csv("data/raw.csv", sep=";")
varejo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [74]:
varejo.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.00000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.08989,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.24754,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.00000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.00000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.00000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.00000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.00000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

In [75]:
print(varejo.columns)
print('-' * 50)
print(varejo.dtypes)

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')
--------------------------------------------------
DATA            object
CO_ID            int64
CL_ID            int64
CL_GENERO       object
CL_EC            int64
CL_FHL           int64
CL_SEG          object
PR_ID            int64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

In [76]:
print("*** Primeiras 5 linhas ***")
print("")
print(varejo.head())

*** Primeiras 5 linhas ***

         DATA  CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID     PR_CAT  \
0  01/02/2019   1000    534         M      4       1      C     67    BEBIDAS
1  01/02/2019   1000    534         M      4       1      C     70    BEBIDAS
2  01/02/2019   1000    534         M      4       1      C    178    HIGIENE
3  01/02/2019   1000    534         M      4       1      C      4  ALIMENTOS
4  01/02/2019   1000    534         M      4       1      C    175    LIMPEZA

                PR_NOME  Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
0  REFRIGERANTE GUARANA          NaN          NaN          NaN          NaN
1   REFRIGERANTE OUTROS          NaN          NaN          NaN          NaN
2       LENCO UMEDECIDO          NaN          NaN          NaN          NaN
3               ABACAXI          NaN          NaN          NaN          NaN
4     LIMPADOR MULTIUSO          NaN          NaN          NaN          NaN

In [77]:
print("*** Validação do identificador de compra (CO_ID) ***")
print("")
print(f"Total de CO_ID únicos: {varejo['CO_ID'].nunique()}")
print(f"Total de linhas: {len(varejo)}")
print("Média de itens por compra:", round(len(varejo) / varejo['CO_ID'].nunique(), 2))

*** Validação do identificador de compra (CO_ID) ***

Total de CO_ID únicos: 18471
Total de linhas: 830000
Média de itens por compra: 44.94

In [78]:
print("*** Quantos NaN, NULL, N/A ou ' '? ***")
print("")
varejo = varejo.replace({'NULL': np.nan, 'N/A': np.nan, '': np.nan})
print("Ordenando colunas com maior número de valores nulos:")
print("")
print(varejo.isnull().sum().sort_values(ascending=False))

*** Quantos NaN, NULL, N/A ou ' '? ***

Ordenando colunas com maior número de valores nulos:

Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
dtype: int64

In [79]:
print("*** Quantas duplicadas? ***")
print("")
print(varejo.duplicated().sum())
print("")
print("*** Quais são as colunas duplicadas: ***")
print("")
print(varejo[varejo.duplicated()])

*** Quantas duplicadas? ***

96553

*** Quais são as colunas duplicadas: ***

              DATA   CO_ID  CL_ID CL_GENERO  CL_EC  CL_FHL CL_SEG  PR_ID  \
19      01/02/2019    1000    534         M      4       1      C     13
40      01/02/2019    1000    534         M      4       1      C      4
46      01/02/2019    1000    534         M      4       1      C     11
49      01/02/2019    1000    534         M      4       1      C     69
50      01/02/2019    1000    534         M      4       1      C    218
...            ...     ...    ...       ...    ...     ...    ...    ...
829989  19/08/2022  919822    155         F      2       0      B     34
829992  19/08/2022  919822    155         F      2       0      B     30
829995  19/08/2022  919822    155         F      2       0      B    183
829996  19/08/2022  919822    155         F      2       0      B     56
829997  19/08/2022  919822    155         F      2       0      B    227

           PR_CAT             PR_NOME  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
19      ALIMENTOS              BANANA          NaN          NaN          NaN
40      ALIMENTOS             ABACAXI          NaN          NaN          NaN
46      ALIMENTOS              AZEITE          NaN          NaN          NaN
49        BEBIDAS  REFRIGERANTE LIMaO          NaN          NaN          NaN
50      ALIMENTOS  BIFE DE COXAO MOLE          NaN          NaN          NaN
...           ...                 ...          ...          ...          ...
829989  ALIMENTOS             KETCHUP          NaN          NaN          NaN
829992  ALIMENTOS       FILE DE PEIXE          NaN          NaN          NaN
829995  ALIMENTOS             KETCHUP          NaN          NaN          NaN
829996  ALIMENTOS    QUEIJO MUSSARELA          NaN          NaN          NaN
829997  ALIMENTOS               ARROZ          NaN          NaN          NaN

        Unnamed: 13
19              NaN
40              NaN
46              NaN
49              NaN
50              NaN
...             ...
829989          NaN
829992          NaN
829995          NaN
829996          NaN
829997          NaN

[96553 rows x 14 columns]

In [80]:
print("*** Duplicatas (amostra): ***")
varejo[varejo.duplicated(keep=False)].head(20)

*** Duplicatas (amostra): ***

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
68,01/02/2019,1078,290,F,1,0,B,144,BEBIDAS,REFRIGERANTE COLA,NaN,NaN,NaN,NaN
69,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE,NaN,NaN,NaN,NaN
70,01/02/2019,1078,290,F,1,0,B,23,ALIMENTOS,COGUMELOS,NaN,NaN,NaN,NaN
73,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA,NaN,NaN,NaN,NaN
76,01/02/2019,1078,290,F,1,0,B,125,HIGIENE,TINTURAS,NaN,NaN,NaN,NaN
77,01/02/2019,1078,290,F,1,0,B,210,ACESSORIOS,CHUPETA,NaN,NaN,NaN,NaN
78,01/02/2019,1078,290,F,1,0,B,99,LIMPEZA,DESINFETANTE,NaN,NaN,NaN,NaN
79,01/02/2019,1078,290,F,1,0,B,156,HIGIENE,PASTA DE DENTE,NaN,NaN,NaN,NaN

In [81]:
print("*** Análise do CO_ID 1000 para identificação de linhas repetidas: ***")
varejo[varejo["CO_ID"] == 1000]

*** Análise do CO_ID 1000 para identificação de linhas repetidas: ***

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,01/02/2019,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,01/02/2019,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,01/02/2019,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN
10,01/02/2019,1000,534,M,4,1,C,182,ALIMENTOS,LATA DE ERVILHA,NaN,NaN,NaN,NaN
11,01/02/2019,1000,534,M,4,1,C,86,HIGIENE,PRESERVATIVO,NaN,NaN,NaN,NaN
12,01/02/2019,1000,534,M,4,1,C,221,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
13,01/02/2019,1000,534,M,4,1,C,200,LIMPEZA,DETERGENTE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
16,01/02/2019,1000,534,M,4,1,C,84,HIGIENE,PAPEL HIGIENICO,NaN,NaN,NaN,NaN
17,01/02/2019,1000,534,M,4,1,C,121,ALIMENTOS,UVA,NaN,NaN,NaN,NaN
18,01/02/2019,1000,534,M,4,1,C,176,LIMPEZA,LIMPA VIDROS,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
20,01/02/2019,1000,534,M,4,1,C,136,ALIMENTOS,RICOTA,NaN,NaN,NaN,NaN
21,01/02/2019,1000,534,M,4,1,C,108,LIMPEZA,REMOVEDOR,NaN,NaN,NaN,NaN
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
23,01/02/2019,1000,534,M,4,1,C,143,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
24,01/02/2019,1000,534,M,4,1,C,149,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
25,01/02/2019,1000,534,M,4,1,C,61,ALIMENTOS,SARDINHA,NaN,NaN,NaN,NaN
26,01/02/2019,1000,534,M,4,1,C,64,ALIMENTOS,UVA,NaN,NaN,NaN,NaN
27,01/02/2019,1000,534,M,4,1,C,191,HIGIENE,FRALDA,NaN,NaN,NaN,NaN
28,01/02/2019,1000,534,M,4,1,C,189,ALIMENTOS,GRANOLA,NaN,NaN,NaN,NaN
29,01/02/2019,1000,534,M,4,1,C,135,LIMPEZA,RODO,NaN,NaN,NaN,NaN
30,01/02/2019,1000,534,M,4,1,C,226,ALIMENTOS,ARROZ INTEGRAL,NaN,NaN,NaN,NaN
31,01/02/2019,1000,534,M,4,1,C,209,ALIMENTOS,COGUMELOS,NaN,NaN,NaN,NaN
32,01/02/2019,1000,534,M,4,1,C,52,ALIMENTOS,PATE,NaN,NaN,NaN,NaN
33,01/02/2019,1000,534,M,4,1,C,160,ALIMENTOS,PALMITO,NaN,NaN,NaN,NaN
34,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN
35,01/02/2019,1000,534,M,4,1,C,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
36,01/02/2019,1000,534,M,4,1,C,123,LIMPEZA,TIRA MANCHA,NaN,NaN,NaN,NaN
37,01/02/2019,1000,534,M,4,1,C,25,ALIMENTOS,CORACAO DE FRANGO,NaN,NaN,NaN,NaN
38,01/02/2019,1000,534,M,4,1,C,229,ALIMENTOS,ALMONDEGA,NaN,NaN,NaN,NaN
39,01/02/2019,1000,534,M,4,1,C,155,ALIMENTOS,PATE,NaN,NaN,NaN,NaN
40,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
41,01/02/2019,1000,534,M,4,1,C,132,HIGIENE,SABONETE,NaN,NaN,NaN,NaN
42,01/02/2019,1000,534,M,4,1,C,23,ALIMENTOS,COGUMELOS,NaN,NaN,NaN,NaN
43,01/02/2019,1000,534,M,4,1,C,24,ALIMENTOS,COPA SUINA,NaN,NaN,NaN,NaN
44,01/02/2019,1000,534,M,4,1,C,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
45,01/02/2019,1000,534,M,4,1,C,66,BEBIDAS,REFRIGERANTE COLA,NaN,NaN,NaN,NaN
46,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
47,01/02/2019,1000,534,M,4,1,C,68,BEBIDAS,REFRIGERANTE LARANJA,NaN,NaN,NaN,NaN
48,01/02/2019,1000,534,M,4,1,C,88,HIGIENE,REPELENTE,NaN,NaN,NaN,NaN
49,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO,NaN,NaN,NaN,NaN
50,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
51,01/02/2019,1000,534,M,4,1,C,225,ALIMENTOS,ATUM,NaN,NaN,NaN,NaN

In [82]:
print("*** Tratamento de duplicadas ***")
print("")
print(f"Encontradas {varejo.duplicated().sum()} linhas duplicadas.")
print("Decisão: manter, pois podem representar múltiplas unidades do mesmo produto")
print("em uma mesma compra (não é possível confirmar erro no cadastro).")

*** Tratamento de duplicadas ***

Encontradas 96553 linhas duplicadas.
Decisão: manter, pois podem representar múltiplas unidades do mesmo produto
em uma mesma compra (não é possível confirmar erro no cadastro).

In [83]:

print("*** Removendo as colunas inteiramente nulas ***")
print("")
varejo = varejo.dropna(axis=1, how='all')
print("*** Info ***")
print("")
varejo.info()
print("*** Tem ainda Nan? ***")
print("")
print(varejo.isnull().sum())

*** Removendo as colunas inteiramente nulas ***

*** Info ***

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  object
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: int64(5), object(5)
memory usage: 63.3+ MB
*** Tem ainda Nan? ***

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [84]:
print("*** Tratamento de Nulos ***")
print("")
print("As únicas colunas com nulos eram Unnamed:10,11,12,13 (100% nulas)")
print("Opção: removidas pois não acrescentam informação.")
print("Nenhuma outra coluna possui valores nulos após a limpeza inicial.")

*** Tratamento de Nulos ***

As únicas colunas com nulos eram Unnamed:10,11,12,13 (100% nulas)
Opção: removidas pois não acrescentam informação.
Nenhuma outra coluna possui valores nulos após a limpeza inicial.

In [85]:

print("*** Tem algum valor em alguma coluna inconsistente ou incorreto? ***")
print("")
print("*** Na coluna PR_CAT: ***")
print("")
print(varejo["PR_CAT"].unique())

*** Tem algum valor em alguma coluna inconsistente ou incorreto? ***

*** Na coluna PR_CAT: ***

['BEBIDAS' 'HIGIENE' 'ALIMENTOS' 'LIMPEZA' 'ACESSORIOS' 'PET' '#N/D']

In [86]:

print("Na coluna PR_NOME")
print("")
print(varejo["PR_NOME"].unique())

Na coluna PR_NOME

['REFRIGERANTE GUARANA' 'REFRIGERANTE OUTROS' 'LENCO UMEDECIDO' 'ABACAXI'
 'LIMPADOR MULTIUSO' 'HASTES FLEXIVEIS' 'MORTADELA' 'AZEITE' 'AMACIANTE'
 'ENERGETICO' 'LATA DE ERVILHA' 'PRESERVATIVO' 'BANANA' 'DETERGENTE'
 'BIFE DE COXAO MOLE' 'PAPEL HIGIENICO' 'UVA' 'LIMPA VIDROS' 'RICOTA'
 'REMOVEDOR' 'REFRIGERANTE LIMaO' 'QUEIJO MUSSARELA' 'SARDINHA' 'FRALDA'
 'GRANOLA' 'RODO' 'ARROZ INTEGRAL' 'COGUMELOS' 'PATE' 'PALMITO' 'ATUM'
 'TIRA MANCHA' 'CORACAO DE FRANGO' 'ALMONDEGA' 'SABONETE' 'COPA SUINA'
 'KETCHUP' 'REFRIGERANTE COLA' 'REFRIGERANTE LARANJA' 'REPELENTE'
 'LEITE CONDENSADO' 'ALCOOL' 'MORDEDOR' 'ESCOVA DE DENTE'
 'RACAO UMIDA PARA GATOS' 'OVOS' 'MAMAO PAPAYA' 'SABAO' 'CAFE'
 'LUSTRA MOVEIS' 'CONDICIONADOR' 'SALGADINHOS DE MILHO' 'LEITE'
 'DESINFETANTE' 'CHUPETA' 'FIXADOR' 'ALHO' 'TINTURAS' 'PASTA DE DENTE'
 'RACAO SECA PARA CAES' 'RACAO UMIDA PARA CAES' '#N/D' 'HIDRATANTE'
 'AGUA SANITARIA' 'SNACKS' 'BATATA' 'SHAMPOO' 'LATA DE MILHO' 'SALGADINHO'
 'QUEIJO DE CABRA' 'ODORIZADOR' 'LINGUICA' 'REQUEIJAO' 'ACHOCOLATADO'
 'BISCOITO' 'FIO DENTAL' 'FILE DE PEIXE' 'PROTETOR SOLAR' 'GEL' 'MAMAO'
 'CENOURA' 'TOMATE' 'LIMPADOR PERFUMADO' 'CHA' 'LIMAO' 'PRESUNTO COZIDO'
 'SABAO EM PO' 'DANETTE' 'CERA' 'PAPINHA INFANTIL' 'TALCO' 'TIRA LIMO'
 'FEIJAO' 'MODELADOR' 'VASSOURA' 'MACARRAO INSTANTANEO' 'DESENGORDURANTE'
 'RACAO SECA PARA GATOS' 'CREME' 'INSETICIDA' 'BATATA DOCE' 'DOCE'
 'PAO DE FORMA' 'MACARRAO' 'IOGURTE' 'BALDE' 'BROCOLIS' 'AZEITONA'
 'HAMBUGUER' 'ALIMENTO PARA PASSARO' 'CEBOLA' 'ENXAGUANTE BUCAL' 'MANGA'
 'COXA E SOBRECOXA DE FRANGO' 'ABACATE' 'ARROZ' 'ABSORVENTE'
 'MOLHO BARBECUE']

In [87]:
print("*** Verificando quantas vezes aparece cada valor: ***")
print("")
print(varejo["PR_NOME"].value_counts())

*** Verificando quantas vezes aparece cada valor: ***

PR_NOME
PRESUNTO COZIDO          14381
SARDINHA                  7490
GEL                       7399
BANANA                    7385
DESENGORDURANTE           7378
                         ...
#N/D                      3650
ABSORVENTE                3639
ALCOOL                    3611
ALIMENTO PARA PASSARO     3605
ALHO                      3574
Name: count, Length: 118, dtype: int64

In [88]:


varejo["PR_CAT"] = varejo["PR_CAT"].replace("#N/D","SEM CATEGORIA")
varejo["PR_NOME"] = varejo["PR_NOME"].replace("#N/D","PRODUTO DESCONHECIDO")

print("")
print("*** Ainda existe #N/D? ***")
print("")
print(varejo["PR_CAT"].unique())
print("")
print("*** Na coluna PR_NOME: ***")
print("")
print(varejo["PR_NOME"].unique())
print("")
print(varejo["PR_NOME"].value_counts())

*** Ainda existe #N/D? ***

['BEBIDAS' 'HIGIENE' 'ALIMENTOS' 'LIMPEZA' 'ACESSORIOS' 'PET'
 'SEM CATEGORIA']

*** Na coluna PR_NOME: ***

['REFRIGERANTE GUARANA' 'REFRIGERANTE OUTROS' 'LENCO UMEDECIDO' 'ABACAXI'
 'LIMPADOR MULTIUSO' 'HASTES FLEXIVEIS' 'MORTADELA' 'AZEITE' 'AMACIANTE'
 'ENERGETICO' 'LATA DE ERVILHA' 'PRESERVATIVO' 'BANANA' 'DETERGENTE'
 'BIFE DE COXAO MOLE' 'PAPEL HIGIENICO' 'UVA' 'LIMPA VIDROS' 'RICOTA'
 'REMOVEDOR' 'REFRIGERANTE LIMaO' 'QUEIJO MUSSARELA' 'SARDINHA' 'FRALDA'
 'GRANOLA' 'RODO' 'ARROZ INTEGRAL' 'COGUMELOS' 'PATE' 'PALMITO' 'ATUM'
 'TIRA MANCHA' 'CORACAO DE FRANGO' 'ALMONDEGA' 'SABONETE' 'COPA SUINA'
 'KETCHUP' 'REFRIGERANTE COLA' 'REFRIGERANTE LARANJA' 'REPELENTE'
 'LEITE CONDENSADO' 'ALCOOL' 'MORDEDOR' 'ESCOVA DE DENTE'
 'RACAO UMIDA PARA GATOS' 'OVOS' 'MAMAO PAPAYA' 'SABAO' 'CAFE'
 'LUSTRA MOVEIS' 'CONDICIONADOR' 'SALGADINHOS DE MILHO' 'LEITE'
 'DESINFETANTE' 'CHUPETA' 'FIXADOR' 'ALHO' 'TINTURAS' 'PASTA DE DENTE'
 'RACAO SECA PARA CAES' 'RACAO UMIDA PARA CAES' 'PRODUTO DESCONHECIDO'
 'HIDRATANTE' 'AGUA SANITARIA' 'SNACKS' 'BATATA' 'SHAMPOO' 'LATA DE MILHO'
 'SALGADINHO' 'QUEIJO DE CABRA' 'ODORIZADOR' 'LINGUICA' 'REQUEIJAO'
 'ACHOCOLATADO' 'BISCOITO' 'FIO DENTAL' 'FILE DE PEIXE' 'PROTETOR SOLAR'
 'GEL' 'MAMAO' 'CENOURA' 'TOMATE' 'LIMPADOR PERFUMADO' 'CHA' 'LIMAO'
 'PRESUNTO COZIDO' 'SABAO EM PO' 'DANETTE' 'CERA' 'PAPINHA INFANTIL'
 'TALCO' 'TIRA LIMO' 'FEIJAO' 'MODELADOR' 'VASSOURA'
 'MACARRAO INSTANTANEO' 'DESENGORDURANTE' 'RACAO SECA PARA GATOS' 'CREME'
 'INSETICIDA' 'BATATA DOCE' 'DOCE' 'PAO DE FORMA' 'MACARRAO' 'IOGURTE'
 'BALDE' 'BROCOLIS' 'AZEITONA' 'HAMBUGUER' 'ALIMENTO PARA PASSARO'
 'CEBOLA' 'ENXAGUANTE BUCAL' 'MANGA' 'COXA E SOBRECOXA DE FRANGO'
 'ABACATE' 'ARROZ' 'ABSORVENTE' 'MOLHO BARBECUE']

PR_NOME
PRESUNTO COZIDO          14381
SARDINHA                  7490
GEL                       7399
BANANA                    7385
DESENGORDURANTE           7378
                         ...
PRODUTO DESCONHECIDO      3650
ABSORVENTE                3639
ALCOOL                    3611
ALIMENTO PARA PASSARO     3605
ALHO                      3574
Name: count, Length: 118, dtype: int64

In [89]:
print("*** Relatório dos problemas identificados ***")
print("")
print(f"1. Colunas totalmente vazias: Unnamed:10,11,12,13 (removidas)")
print(f"2. Valores '#N/D' encontrados nas colunas PR_CAT e PR_NOME")
print(f"3. Registros duplicados: {varejo.duplicated().sum()} registros (mantidos pois podem representar múltiplas unidades do mesmo produto)")

*** Relatório dos problemas identificados ***

1. Colunas totalmente vazias: Unnamed:10,11,12,13 (removidas)
2. Valores '#N/D' encontrados nas colunas PR_CAT e PR_NOME
3. Registros duplicados: 96553 registros (mantidos pois podem representar múltiplas unidades do mesmo produto)

In [90]:
print("*** Transformando str em datetime ***")
print("")
varejo["DATA"]=pd.to_datetime(varejo["DATA"],dayfirst = True)
varejo.info()

*** Transformando str em datetime ***

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  datetime64[ns]
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  object
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  object
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  object
 9   PR_NOME    830000 non-null  object
dtypes: datetime64[ns](1), int64(5), object(4)
memory usage: 63.3+ MB

In [91]:
# Exportando base de dados limpa
varejo.to_csv('data/clean.csv')

In [92]:
print("")
print("*** Estatísticas da coluna CL_FHL: Número de filhos do cliente ***")
print("")
print("Contagem(count), média(mean), desvio padrão(std), mínimo(min), quartis(25% e 75%),  mediana(50%), máximo(max):")
print(varejo["CL_FHL"].describe())
print("")
print("*** Moda(mode) ***")
print(varejo["CL_FHL"].mode())

*** Estatísticas da coluna CL_FHL: Número de filhos do cliente ***

Contagem(count), média(mean), desvio padrão(std), mínimo(min), quartis(25% e 75%),  mediana(50%), máximo(max):
count    830000.00000
mean          1.14654
std           1.41696
min           0.00000
25%           0.00000
50%           0.00000
75%           2.00000
max           4.00000
Name: CL_FHL, dtype: float64

*** Moda(mode) ***
0    0
Name: CL_FHL, dtype: int64

In [93]:
Q1  = varejo["CL_FHL"].quantile(0.25)
Q3  = varejo["CL_FHL"].quantile(0.75)
IQR = Q3 - Q1

lim_inf = Q1 - 1.5 * IQR
lim_sup = Q3 + 1.5 * IQR

print(f"Faixa normal: [{lim_inf:.2f}, {lim_sup:.2f}]")

mascara = (varejo['CL_FHL'] < lim_inf) | (varejo['CL_FHL'] > lim_sup)
print("")
print(f"Outliers encontrados: {mascara.sum()}")
print("")
print(varejo[mascara][['CO_ID', 'CL_FHL']])

Faixa normal: [-3.00, 5.00]

Outliers encontrados: 0

Empty DataFrame
Columns: [CO_ID, CL_FHL]
Index: []

In [94]:
# Calcular o Z-Score de uma coluna
media  = varejo['CL_FHL'].mean()    # média dos salários
desvio = varejo['CL_FHL'].std()     # desvio padrão

z_scores = (varejo['CL_FHL'] - media) / desvio
# z = 0   → valor igual à média
# z = 2   → 2 desvios ACIMA da média
# z = -3  → 3 desvios ABAIXO = outlier!

# Filtrar quem tem z muito alto ou muito baixo
outliers = varejo[z_scores.abs() > 3]
print("")
print(f"Outliers (|z| > 3): {len(outliers)}")
print("")
print(outliers[['CL_FHL']])

Outliers (|z| > 3): 0

Empty DataFrame
Columns: [CL_FHL]
Index: []

In [95]:

print("*** Qual gênero compra mais produtos? ***")
print("")
print(varejo.groupby(["CL_GENERO"]).size().sort_values(ascending=False))

*** Qual gênero compra mais produtos? ***

CL_GENERO
F    432576
M    397424
dtype: int64

In [96]:
print("*** Vendas por segmento econômico: ***")
print("")
print(varejo.groupby(['CL_SEG']).size().sort_values(ascending=False))

*** Vendas por segmento econômico: ***

CL_SEG
B    530163
C    232101
A     67736
dtype: int64

In [97]:
print("*** Qual a categoria mais vendida? ***")
print("")
print(varejo.groupby(["PR_CAT"]).size().sort_values(ascending=False))

*** Qual a categoria mais vendida? ***

PR_CAT
ALIMENTOS        434767
HIGIENE          155574
LIMPEZA          145754
BEBIDAS           43299
PET               32399
ACESSORIOS        14557
SEM CATEGORIA      3650
dtype: int64

In [98]:
print("*** Quantidade de produtos vendidos de cada mês: ***")
print("")
print(varejo.groupby(varejo["DATA"].dt.month).size())

*** Quantidade de produtos vendidos de cada mês: ***

DATA
1     83963
2     76201
3     64371
4     66935
5     82275
6     67808
7     68983
8     65609
9     68594
10    73900
11    40912
12    70449
dtype: int64

In [99]:
print("*** Meses com maior quantidade de produtos vendidos: ***")
print("")
print(varejo.groupby(varejo["DATA"].dt.month).size().sort_values(ascending=False))

*** Meses com maior quantidade de produtos vendidos: ***

DATA
1     83963
5     82275
2     76201
10    73900
12    70449
7     68983
9     68594
6     67808
4     66935
8     65609
3     64371
11    40912
dtype: int64

In [100]:
print("*** Meses com maior quantidade de produtos vendidos(%) ***")
print("")

meses = varejo.groupby(varejo["DATA"].dt.month).size()

percentual = (meses / len(varejo)) * 100

print(percentual.sort_values(ascending=False).round(2))

*** Meses com maior quantidade de produtos vendidos(%) ***

DATA
1     10.12
5      9.91
2      9.18
10     8.90
12     8.49
7      8.31
9      8.26
6      8.17
4      8.06
8      7.90
3      7.76
11     4.93
dtype: float64

In [101]:

print("Quantos produtos vendidos em cada ano:")
print("")
print(varejo["DATA"].dt.year.value_counts().sort_index())

print("-"*50)
print("Quando foi o primeiro e o último registro na base de dados de venda de produtos:")
print("")
print("Primeiro registro:",varejo["DATA"].min())
print("Último registro",varejo["DATA"].max())

Quantos produtos vendidos em cada ano:

DATA
2019    199036
2020    218367
2021    245259
2022    167338
Name: count, dtype: int64
--------------------------------------------------
Quando foi o primeiro e o último registro na base de dados de venda de produtos:

Primeiro registro: 2019-01-04 00:00:00
Último registro 2022-12-08 00:00:00

In [102]:
print("*** Conclusões da análise ***")
print("1. Janeiro, Maio e Fevereiro concentram os maiores volumes de vendas.")
print("2. Clientes do gênero feminino representam 52,1% das compras.")
print("3. A categoria alimentos responde por mais da metade das vendas (52,38%).")
print("4. O perfil predominante do varejo é de consumidores de renda média a média-baixa.")
print("5. A maioria dos clientes não tem filhos (mediana = 0, moda = 0).")
print("6. Não foram identificados outliers significativos na coluna de filhos.")
print("7. A base ainda tem limitação: categorias 'separado' e 'divorciado' podem ser agrupadas.")

*** Conclusões da análise ***
1. Janeiro, Maio e Fevereiro concentram os maiores volumes de vendas.
2. Clientes do gênero feminino representam 52,1% das compras.
3. A categoria alimentos responde por mais da metade das vendas (52,38%).
4. O perfil predominante do varejo é de consumidores de renda média a média-baixa.
5. A maioria dos clientes não tem filhos (mediana = 0, moda = 0).
6. Não foram identificados outliers significativos na coluna de filhos.
7. A base ainda tem limitação: categorias 'separado' e 'divorciado' podem ser agrupadas.